version: '3'
services:  
  #MySQL Service
  db:
    container_name: db
    restart: unless-stopped
    env_file: ./mysql/.env.dev
    build: ./mysql
    tty: true
    ports:
      - "3306:3306"
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    depends_on: 
      - db
    links: 
      - db

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: on-failure
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local